# CSAT subject areas (all exam areas). One scheme; loaded after seed.sql and
# csat-ontology. Reference: shared/prompt/documentation (ontology scope).

[[concept_scheme]]
id = "csat-subjects"
name = "CSAT subject areas"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-korean"
pref_label = "Korean"
path = "subj.korean"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-math-ga"
pref_label = "Mathematics (GA)"
path = "subj.math.ga"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-math-na"
pref_label = "Mathematics (NA)"
path = "subj.math.na"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-english"
pref_label = "English"
path = "subj.english"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-social"
pref_label = "Social studies"
path = "subj.social"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-science"
pref_label = "Science"
path = "subj.science"

[[concept]]
scheme_id = "csat-subjects"
code = "subj-l2"
pref_label = "Second foreign language"
path = "subj.l2"
