# Global classification standards. ISCED 2011 (level), ISCED-F 2013 (field), Bloom revised.
# Loaded by run-seed-ontology.ts. No CEFR/PISA.

[[concept_scheme]]
id = "isced"
name = "ISCED 2011: Education level"

[[concept]]
scheme_id = "isced"
code = "isced-0"
pref_label = "Early childhood education"
path = "isced.0"

[[concept]]
scheme_id = "isced"
code = "isced-1"
pref_label = "Primary education"
path = "isced.1"

[[concept]]
scheme_id = "isced"
code = "isced-2"
pref_label = "Lower secondary education"
path = "isced.2"

[[concept]]
scheme_id = "isced"
code = "isced-3"
pref_label = "Upper secondary education"
path = "isced.3"

[[concept]]
scheme_id = "isced"
code = "isced-4"
pref_label = "Post-secondary non-tertiary"
path = "isced.4"

[[concept]]
scheme_id = "isced"
code = "isced-5"
pref_label = "Short-cycle tertiary"
path = "isced.5"

[[concept]]
scheme_id = "isced"
code = "isced-6"
pref_label = "Bachelor or equivalent"
path = "isced.6"

[[concept]]
scheme_id = "isced"
code = "isced-7"
pref_label = "Master or equivalent"
path = "isced.7"

[[concept]]
scheme_id = "isced"
code = "isced-8"
pref_label = "Doctoral or equivalent"
path = "isced.8"

[[concept_scheme]]
id = "iscedf"
name = "ISCED-F 2013: Field of education"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-00"
pref_label = "Generic programmes and qualifications"
path = "iscedf.00"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-01"
pref_label = "Education"
path = "iscedf.01"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-02"
pref_label = "Arts and humanities"
path = "iscedf.02"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-03"
pref_label = "Social sciences, journalism and information"
path = "iscedf.03"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-04"
pref_label = "Business, administration and law"
path = "iscedf.04"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-05"
pref_label = "Natural sciences, mathematics and statistics"
path = "iscedf.05"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-06"
pref_label = "Information and communication technologies"
path = "iscedf.06"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-07"
pref_label = "Engineering, manufacturing and construction"
path = "iscedf.07"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-08"
pref_label = "Agriculture, forestry, fisheries and veterinary"
path = "iscedf.08"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-09"
pref_label = "Health and welfare"
path = "iscedf.09"

[[concept]]
scheme_id = "iscedf"
code = "iscedf-10"
pref_label = "Services"
path = "iscedf.10"

[[concept_scheme]]
id = "bloom"
name = "Bloom's taxonomy (revised): Cognitive level"

[[concept]]
scheme_id = "bloom"
code = "bloom-1"
pref_label = "Remember (define, list, name)"
path = "bloom.1"

[[concept]]
scheme_id = "bloom"
code = "bloom-2"
pref_label = "Understand (summarize, classify, explain)"
path = "bloom.2"

[[concept]]
scheme_id = "bloom"
code = "bloom-3"
pref_label = "Apply (solve, demonstrate, use)"
path = "bloom.3"

[[concept]]
scheme_id = "bloom"
code = "bloom-4"
pref_label = "Analyze (contrast, examine, organize)"
path = "bloom.4"

[[concept]]
scheme_id = "bloom"
code = "bloom-5"
pref_label = "Evaluate (judge, critique, assess)"
path = "bloom.5"

[[concept]]
scheme_id = "bloom"
code = "bloom-6"
pref_label = "Create (design, construct, plan)"
path = "bloom.6"
