academic_year_start_mmdd = "03-02"
recurring = ["01-01","03-01","05-05","06-06","08-15","10-03","10-09","12-25"]

[by_year]
2025 = ["2025-10-05","2025-10-06","2025-10-07","2025-10-08"]
2026 = ["2026-09-24","2026-09-25","2026-09-26","2026-09-27"]
